@php
    $faqs = [
        ['How do I get from Velana International Airport to Himmafushi?', 'Scheduled speedboats connect Velana International Airport and Male with Himmafushi. The Male crossing is around 20 minutes; airport journey times vary by route, pickup sequence, weather, and operator. Current published guest fares on Himmafushi.travel start from USD 10 from Male and USD 25 from the airport. Always choose your date and confirm the live schedule before travel.'],
        ['What is the best time of year to surf Jailbreaks in Himmafushi?', 'The main surf window generally runs from March or April through October, with the strongest and most consistent southwest-monsoon swells commonly arriving between May and August. Shoulder periods can offer a useful balance of conditions and availability, but daily waves are never guaranteed.'],
        ['Is there an ATM on Himmafushi?', 'Yes. Bank of Maldives lists a BML ATM on Himmafushi. It dispenses Maldivian Rufiyaa, but visitors should still carry some backup cash and confirm card and withdrawal conditions with their bank.'],
        ['Can tourists wear bikinis on Himmafushi?', 'Bikinis and swimwear should be used only at the designated tourist beach. Himmafushi is an inhabited Muslim island, so visitors should wear modest clothing through the residential village and respect local customs.'],
    ];
    $faqSchema = ['@context' => 'https://schema.org', '@type' => 'FAQPage', 'mainEntity' => collect($faqs)->map(fn ($faq) => ['@type' => 'Question', 'name' => $faq[0], 'acceptedAnswer' => ['@type' => 'Answer', 'text' => $faq[1]]])->all()];
@endphp
<x-layouts.app title="Himmafushi Island Guide | How to Reach, Jailbreaks Surf & Local Life" description="Plan your trip to Himmafushi, Maldives. Learn how to get here, surf Jailbreaks, find guesthouses, explore local life and arrange island experiences.">
    @push('structured-data')<script type="application/ld+json">{!! json_encode($faqSchema, JSON_UNESCAPED_SLASHES) !!}</script>@endpush
    <section class="service-hero island-guide-hero"><img src="{{ asset('images/himmafushi-hero.png') }}" alt="Aerial view of Himmafushi island in North Male Atoll"><div class="page-shell"><p class="eyebrow">North Male Atoll, Maldives</p><h1>Himmafushi Island Guide</h1><p>Close to Malé and the airport, famous for Jailbreaks, and alive with local businesses, boats, food, and everyday island culture.</p><div class="service-hero-actions"><a class="button" href="{{ route('guesthouses.index') }}">Find a place to stay</a><a class="button button-outline-light" href="{{ route('transfers.index') }}">Plan your transfer</a></div></div></section>

    <section class="section"><div class="page-shell island-guide-intro"><div><p class="eyebrow">A local island with real character</p><h2>More than a stop on the map</h2><p>Situated roughly 16 kilometres northeast of Malé in Kaafu Atoll, Himmafushi is one of North Malé Atoll's most accessible inhabited islands. It combines affordable local-island tourism with an active community economy, making it a practical base for surfers, divers, families, and travellers who want to experience the Maldives beyond a resort.</p><p>The island is compact enough to explore on foot. Guesthouses, cafes, shops, the harbour, local neighbourhoods, and the designated tourist beach all sit within a walkable island environment.</p></div><div class="island-quick-facts"><div><span>Atoll</span><strong>North Malé / Kaafu</strong></div><div><span>From Malé</span><strong>About 16 km</strong></div><div><span>Getting here</span><strong>Speedboat or arranged boat</strong></div><div><span>Known for</span><strong>Jailbreaks &amp; local life</strong></div></div></div></section>

    <section class="section section-tint"><div class="page-shell guide-split"><div><p class="eyebrow">Arrive with confidence</p><h2>Getting to Himmafushi</h2><p>Scheduled speedboats connect Himmafushi with Malé and Velana International Airport. The Malé crossing is typically around 20 minutes; airport routing can take longer depending on the operator and pickup sequence. Private boats can also be arranged for late arrivals, families, surf groups, and larger teams.</p><div class="arrival-tip"><strong>Arrival tip</strong><p>Book ahead and leave a comfortable buffer after your flight. Tell the operator in advance if you are travelling with surfboards, diving equipment, large luggage, or cargo so deck space can be confirmed.</p></div><div class="guide-actions"><a class="button" href="{{ route('transfers.index') }}">See schedules and fares</a><a class="text-link" href="{{ route('private-transfers') }}">Arrange a private transfer</a></div></div><aside class="guide-route-card"><span>Typical journey</span><h3>Airport / Malé <b>&rarr;</b> Himmafushi</h3><dl><div><dt>Malé travel time</dt><dd>About 20 minutes</dd></div><div><dt>Guest fare from Malé</dt><dd>From USD 10</dd></div><div><dt>Guest fare from airport</dt><dd>From USD 25</dd></div><div><dt>Private boats</dt><dd>On request</dd></div></dl><small>Times and fares must be confirmed for your selected date.</small></aside></div></section>

    <section class="section"><div class="page-shell"><div class="home-section-heading"><div><p class="eyebrow">Why visit</p><h2>What makes Himmafushi special</h2><p>A small island with ocean access, useful services, and a working community.</p></div></div><div class="island-feature-grid"><article><span>01</span><h3>Jailbreaks &amp; surfing</h3><p>Himmafushi is internationally known as the home base for Jailbreaks, a right-hand reef wave with multiple sections. Sultans, Honky's, Ninjas, and other North Malé Atoll breaks may be reached by locally arranged boats depending on access and conditions.</p><a href="{{ route('surfing') }}">Read the surf guide</a></article><article><span>02</span><h3>Beach &amp; blue water</h3><p>The designated tourist beach offers a place to swim and relax. Local operators arrange reef snorkelling, scuba diving, sandbank trips, dolphin cruises, fishing, and private outings subject to weather.</p><a href="{{ route('activities.index') }}">Explore things to do</a></article><article><span>03</span><h3>Local craftsmanship</h3><p>Himmafushi is not dependent on tourism alone. Boat building, fish processing, shops, services, and small businesses are part of the island's working identity and local economy.</p><a href="{{ route('shops.index') }}">Browse local shops</a></article><article><span>04</span><h3>Guesthouse island stays</h3><p>Stay in locally run accommodation, eat at island cafes, and arrange activities directly. Options range from practical surf stays to comfortable beach-oriented guesthouses.</p><a href="{{ route('guesthouses.index') }}">Find guesthouses</a></article></div></div></section>

    <section class="section section-dark"><div class="page-shell local-life-layout"><div><p class="eyebrow light">Travel thoughtfully</p><h2>Local life and island etiquette</h2><p>Himmafushi is an inhabited Muslim community, not a private resort. Modest clothing is expected through the residential village. Use swimwear only at the designated tourist beach, avoid alcohol, respect prayer times and private spaces, and ask before photographing people.</p><p>Supporting guesthouses, cafes, shops, guides, and boat crews keeps more visitor spending in the local community. Keep beaches and reefs clean, avoid touching coral, and follow operator safety guidance on every marine trip.</p></div><div class="local-life-list"><div><span>Currency</span><strong>MVR and commonly accepted USD</strong></div><div><span>Cash access</span><strong>Bank of Maldives ATM</strong></div><div><span>Getting around</span><strong>Walkable local island</strong></div><div><span>Dress</span><strong>Modest in the village</strong></div></div></div></section>

    <section class="section"><div class="page-shell guide-directory"><div class="home-section-heading"><div><p class="eyebrow">Plan your days</p><h2>Everything Himmafushi in one place</h2></div></div><div class="experience-link-grid"><a href="{{ route('guesthouses.index') }}"><span>01</span><div><h3>Stay</h3><p>Compare guesthouses and request the best available rate.</p></div><strong>&rarr;</strong></a><a href="{{ route('restaurants.index') }}"><span>02</span><div><h3>Eat &amp; drink</h3><p>Find local restaurants, cafes, menus, and island favourites.</p></div><strong>&rarr;</strong></a><a href="{{ route('activities.index') }}"><span>03</span><div><h3>Explore</h3><p>Book surfing, diving, snorkelling, fishing, and excursions.</p></div><strong>&rarr;</strong></a><a href="{{ route('shops.index') }}"><span>04</span><div><h3>Shop locally</h3><p>Discover groceries, souvenirs, essentials, and local services.</p></div><strong>&rarr;</strong></a></div></div></section>

    <section class="section section-tint"><div class="page-shell faq-layout"><div><p class="eyebrow">Visitor questions</p><h2>Himmafushi FAQ</h2><p>Useful answers for planning, with live schedules always taking priority over general guidance.</p></div><div class="faq-list">@foreach($faqs as [$question, $answer])<details><summary>{{ $question }}<span aria-hidden="true">+</span></summary><p>{{ $answer }}</p></details>@endforeach</div></div></section>

    <section class="section"><div class="page-shell service-layout"><div><p class="eyebrow">Plan with local help</p><h2>Ready to visit Himmafushi?</h2><p>We can help with guesthouse rates, transfers, surf stays, excursions, fishing, and complete packages. Travel arrangements can be fulfilled with our travel agency partner, <a class="inline-partner-link" href="https://atollivamaldives.com" target="_blank" rel="noopener">Atolliva Maldives</a>.</p><div class="guide-sources"><span>Information references</span><a href="https://www.environment.gov.mv/v2/download/495/" target="_blank" rel="noopener">Maldives environment island data</a><a href="https://www.bankofmaldives.com.mv/find-us" target="_blank" rel="noopener">Bank of Maldives locations</a><a href="https://jp.mdvmission.gov.mv/images/Visit-Maldives/destination-guide-2025-english.pdf" target="_blank" rel="noopener">Maldives Destination Guide</a></div></div><x-contact-cta title="Ask us about Himmafushi" message="Call or WhatsApp with your travel dates and interests. We will help you find the right stay, transfer, and island experiences." /></div></section>
</x-layouts.app>
