<x-layouts.app title="Surfing in Himmafushi | Jailbreaks Surf Guide & Packages" description="Plan a Himmafushi surf trip around the famous Jailbreaks right-hand reef break. Find the best season, surf guesthouses, transfers and Atolliva Maldives packages.">
    @php
        $faqSchema = [
            '@context' => 'https://schema.org',
            '@type' => 'FAQPage',
            'mainEntity' => [
                ['@type' => 'Question', 'name' => 'When is the best time to surf in Himmafushi?', 'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'The broad surf season runs from around mid-February to November. March to May and September to November can offer an attractive balance of swell and conditions, while May to August often brings the most powerful and consistent swell.']],
                ['@type' => 'Question', 'name' => 'What is Jailbreaks surf break?', 'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Jailbreaks is the famous right-hand reef break beside Himmafushi in North Male Atoll. It has multiple takeoff areas and sections that can connect into long rides.']],
                ['@type' => 'Question', 'name' => 'Can you arrange a Himmafushi surf package?', 'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Yes. Himmafushi.travel can help with surf guesthouses and local planning, while Atolliva Maldives can arrange accommodation, airport transfers and tailored travel packages.']],
            ],
        ];
    @endphp
    @push('structured-data')<script type="application/ld+json">{!! json_encode($faqSchema, JSON_UNESCAPED_SLASHES) !!}</script>@endpush
    <section class="service-hero surf-hero"><img src="{{ asset('images/himmafushi-hero.png') }}" alt="Surfing and island travel in Himmafushi, Maldives"><div class="page-shell"><p class="eyebrow">Surf North Male Atoll</p><h1>Surfing in Himmafushi</h1><p>Stay on the island beside Jailbreaks, one of the Maldives' best-known right-hand reef waves, and let us help arrange your surf guesthouse, airport transfer, and trip package.</p><div class="service-hero-actions"><a class="button" href="tel:+9607779493">Call for best rates</a><a class="button button-outline-light" href="https://wa.me/9607779493?text={{ urlencode('Hello, I am planning a surf trip to Himmafushi and would like the best guesthouse and package rates.') }}" target="_blank" rel="noopener">Plan on WhatsApp</a></div><p class="powered-by">Travel packages arranged with <a href="https://atollivamaldives.com" target="_blank" rel="noopener">AtollivaMaldives.com</a></p></div></section>

    <section class="section surf-intro"><div class="page-shell"><div class="surf-lead"><div><p class="eyebrow">The home of Jailbreaks</p><h2>A local island built for a serious surf trip</h2></div><p>Himmafushi gives surfers a practical local-island base in North Male Atoll, close to Velana International Airport and beside its signature wave. Between sessions you have local guesthouses, cafes, shops, and an island community rather than an isolated resort experience.</p></div><div class="surf-facts"><div><span>Wave</span><strong>Right-hand reef break</strong></div><div><span>Level</span><strong>Intermediate to advanced</strong></div><div><span>Broad season</span><strong>Mid-February-November</strong></div><div><span>Water</span><strong>Warm year-round</strong></div></div></div></section>

    <section class="section section-tint"><div class="page-shell surf-story"><div><p class="eyebrow">The famous wave</p><h2>About Jailbreaks</h2><p>Jailbreaks, also called Jails, is the wave most closely associated with Himmafushi. The name comes from the prison located on the island. It is a right-hander breaking over reef, with a broad wave field, several takeoff zones, and different sections that can link into long rides when the swell, wind, and tide line up.</p><p>The wave can offer open faces and faster, hollower sections. That variety is part of its appeal, but it is still an ocean reef break. Ability requirements change with swell size, tide, wind, and crowd level. Surfers should honestly assess their experience, check current conditions, respect local guidance and lineup etiquette, and use a local surf operator when unfamiliar with the break.</p></div><aside class="surf-callout"><p class="eyebrow">Good to know</p><h3>Come prepared for reef surfing</h3><ul><li>Ask a local operator about tide, access, and current conditions.</li><li>Bring reef-safe sun protection and suitable surf equipment.</li><li>Consider travel insurance that covers your planned surf activity.</li><li>Never treat seasonal guidance as a guarantee of daily waves.</li></ul></aside></div></section>

    <section class="section"><div class="page-shell"><div class="home-section-heading"><div><p class="eyebrow">Choose your window</p><h2>When to book a Himmafushi surf trip</h2><p>Swell and wind vary year to year, but these periods are useful for planning.</p></div></div><div class="surf-season-grid"><article><span>March-May</span><h3>Early-season quality</h3><p>A strong choice for surfers seeking increasingly consistent swell, generally attractive conditions, and dates before the busiest peak.</p></article><article class="is-featured"><span>May-August</span><h3>Most powerful window</h3><p>The southwest monsoon commonly brings the strongest and most consistent Indian Ocean swell. Expect more power and potentially more surfers.</p></article><article><span>September-November</span><h3>Late-season balance</h3><p>A valuable window for lingering swell and potentially lighter conditions as the main season begins to wind down.</p></article></div><p class="service-note"><strong>Our booking advice:</strong> reserve peak-season flights and surf guesthouses early, especially for June-August. For a balance of waves, availability, and fewer peak dates, ask us about March-April or September-October.</p></div></section>

    <section class="section section-dark"><div class="page-shell surf-package"><div><p class="eyebrow light">Stay, transfer, surf</p><h2>Let us build your Himmafushi surf trip</h2><p>Call us for the best available surf guesthouse rates. We can help match your dates and budget with a local stay, arrange airport or private transfers, and connect the practical pieces of the trip.</p><div class="surf-package-links"><a class="button" href="{{ route('guesthouses.index') }}">Browse guesthouses</a><a class="button button-outline-light" href="{{ route('packages') }}">View packages</a></div></div><div class="surf-agency"><span>Travel partner</span><h3>Atolliva Maldives</h3><p>Our travel agency partner can arrange complete Maldives travel packages, including accommodation and transfers for individuals and surf groups.</p><a class="text-link" href="https://atollivamaldives.com" target="_blank" rel="noopener">Visit AtollivaMaldives.com</a></div></div></section>

    <section class="section"><div class="page-shell service-layout"><div><p class="eyebrow">Start planning</p><h2>Tell us about your surf trip</h2><p>Send your travel dates, number of surfers, room preference, ability level, board requirements, and whether you need airport transfers. We will check suitable guesthouses and package options.</p><div class="surf-sources"><h3>Planning references</h3><p>Seasonal and wave guidance was cross-checked against the official Maldives Destination Guide and established surf references. Conditions change daily, so confirm forecasts and local advice before paddling out.</p><a href="https://jp.mdvmission.gov.mv/images/Visit-Maldives/destination-guide-2025-english.pdf" target="_blank" rel="noopener">Maldives Destination Guide</a><a href="https://www.surfline.com/surf-report/jailbreaks/5842041f4e65fad6a7708bdd/spot-guide" target="_blank" rel="noopener">Surfline Jailbreaks guide</a></div></div><x-contact-cta title="Get the best surf stay rates" message="Call or WhatsApp your dates and group size. We can help with surf guesthouses, transfers, and a complete Himmafushi package." /></div></section>
</x-layouts.app>
